import type { CriterionDefinition, ThemeDefinition } from "../types.js";

// ─── Theme 1 — Images ─────────────────────────────────────────────────────────
const theme1: CriterionDefinition[] = [
  {
    id: "1.1",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "full",
    tests: [
      { id: "1.1.1", automated: true },
      { id: "1.1.2", automated: true },
      { id: "1.1.3", automated: true },
      { id: "1.1.4", automated: false },
      { id: "1.1.5", automated: true },
      { id: "1.1.6", automated: true },
      { id: "1.1.7", automated: true },
      { id: "1.1.8", automated: true },
    ],
  },
  {
    id: "1.2",
    theme: 1,
    level: "A",
    wcag: ["1.1.1", "4.1.2"],
    automationLevel: "full",
    tests: [
      { id: "1.2.1", automated: true },
      { id: "1.2.2", automated: true },
      { id: "1.2.3", automated: true },
      { id: "1.2.4", automated: true },
      { id: "1.2.5", automated: true },
      { id: "1.2.6", automated: true },
    ],
  },
  {
    id: "1.3",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [
      { id: "1.3.1", automated: false },
      { id: "1.3.2", automated: false },
      { id: "1.3.3", automated: false },
      { id: "1.3.4", automated: false },
      { id: "1.3.5", automated: false },
      { id: "1.3.6", automated: false },
      { id: "1.3.7", automated: false },
    ],
  },
  {
    id: "1.4",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [
      { id: "1.4.1", automated: false },
      { id: "1.4.2", automated: false },
      { id: "1.4.3", automated: false },
      { id: "1.4.4", automated: false },
      { id: "1.4.5", automated: false },
      { id: "1.4.6", automated: false },
      { id: "1.4.7", automated: false },
      { id: "1.4.8", automated: false },
    ],
  },
  {
    id: "1.5",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [{ id: "1.5.1", automated: false }],
  },
  {
    id: "1.6",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [
      { id: "1.6.1", automated: false },
      { id: "1.6.2", automated: false },
      { id: "1.6.3", automated: false },
      { id: "1.6.4", automated: false },
      { id: "1.6.5", automated: false },
      { id: "1.6.6", automated: false },
      { id: "1.6.7", automated: false },
      { id: "1.6.8", automated: false },
    ],
  },
  {
    id: "1.7",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [
      { id: "1.7.1", automated: false },
      { id: "1.7.2", automated: false },
      { id: "1.7.3", automated: false },
    ],
  },
  {
    id: "1.8",
    theme: 1,
    level: "AA",
    wcag: ["1.4.5"],
    automationLevel: "partial",
    tests: [
      { id: "1.8.1", automated: false },
      { id: "1.8.2", automated: false },
      { id: "1.8.3", automated: false },
      { id: "1.8.4", automated: false },
      { id: "1.8.5", automated: false },
    ],
  },
  {
    id: "1.9",
    theme: 1,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "partial",
    tests: [{ id: "1.9.1", automated: true }],
  },
];

// ─── Theme 2 — Frames ─────────────────────────────────────────────────────────
const theme2: CriterionDefinition[] = [
  {
    id: "2.1",
    theme: 2,
    level: "A",
    wcag: ["4.1.2"],
    automationLevel: "full",
    tests: [{ id: "2.1.1", automated: true }],
  },
  {
    id: "2.2",
    theme: 2,
    level: "A",
    wcag: ["4.1.2"],
    automationLevel: "partial",
    tests: [{ id: "2.2.1", automated: true }],
  },
];

// ─── Theme 3 — Colors ─────────────────────────────────────────────────────────
const theme3: CriterionDefinition[] = [
  {
    id: "3.1",
    theme: 3,
    level: "A",
    wcag: ["1.4.1"],
    automationLevel: "manual",
    tests: [{ id: "3.1.1", automated: false }],
  },
  {
    id: "3.2",
    theme: 3,
    level: "AA",
    wcag: ["1.4.3"],
    automationLevel: "full",
    tests: [
      { id: "3.2.1", automated: true },
      { id: "3.2.2", automated: true },
      { id: "3.2.3", automated: true },
      { id: "3.2.4", automated: true },
      { id: "3.2.5", automated: true },
    ],
  },
  {
    id: "3.3",
    theme: 3,
    level: "AA",
    wcag: ["1.4.11"],
    automationLevel: "full",
    tests: [{ id: "3.3.1", automated: true }],
  },
];

// ─── Theme 4 — Multimedia ─────────────────────────────────────────────────────
const theme4: CriterionDefinition[] = [
  {
    id: "4.1",
    theme: 4,
    level: "A",
    wcag: ["1.2.1"],
    automationLevel: "manual",
    tests: [
      { id: "4.1.1", automated: false },
      { id: "4.1.2", automated: false },
      { id: "4.1.3", automated: false },
    ],
  },
  {
    id: "4.2",
    theme: 4,
    level: "A",
    wcag: ["1.2.1"],
    automationLevel: "manual",
    tests: [
      { id: "4.2.1", automated: false },
      { id: "4.2.2", automated: false },
    ],
  },
  {
    id: "4.3",
    theme: 4,
    level: "A",
    wcag: ["1.2.2"],
    automationLevel: "partial",
    tests: [
      { id: "4.3.1", automated: true },
      { id: "4.3.2", automated: false },
    ],
  },
  {
    id: "4.4",
    theme: 4,
    level: "AA",
    wcag: ["1.2.9"],
    automationLevel: "manual",
    tests: [{ id: "4.4.1", automated: false }],
  },
  {
    id: "4.5",
    theme: 4,
    level: "A",
    wcag: ["1.2.3", "1.2.5"],
    automationLevel: "manual",
    tests: [
      { id: "4.5.1", automated: false },
      { id: "4.5.2", automated: false },
    ],
  },
  {
    id: "4.6",
    theme: 4,
    level: "AA",
    wcag: ["1.2.5"],
    automationLevel: "manual",
    tests: [{ id: "4.6.1", automated: false }],
  },
  {
    id: "4.7",
    theme: 4,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "partial",
    tests: [{ id: "4.7.1", automated: true }],
  },
  {
    id: "4.8",
    theme: 4,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [
      { id: "4.8.1", automated: false },
      { id: "4.8.2", automated: false },
    ],
  },
  {
    id: "4.9",
    theme: 4,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [{ id: "4.9.1", automated: false }],
  },
  {
    id: "4.10",
    theme: 4,
    level: "A",
    wcag: ["1.4.2"],
    automationLevel: "partial",
    tests: [{ id: "4.10.1", automated: true }],
  },
  {
    id: "4.11",
    theme: 4,
    level: "A",
    wcag: ["2.1.1"],
    automationLevel: "partial",
    tests: [
      { id: "4.11.1", automated: false },
      { id: "4.11.2", automated: false },
    ],
  },
  {
    id: "4.12",
    theme: 4,
    level: "A",
    wcag: ["2.1.1"],
    automationLevel: "partial",
    tests: [
      { id: "4.12.1", automated: false },
      { id: "4.12.2", automated: false },
    ],
  },
  {
    id: "4.13",
    theme: 4,
    level: "A",
    wcag: ["4.1.2"],
    automationLevel: "manual",
    tests: [
      { id: "4.13.1", automated: false },
      { id: "4.13.2", automated: false },
    ],
  },
];

// ─── Theme 5 — Tables ─────────────────────────────────────────────────────────
const theme5: CriterionDefinition[] = [
  {
    id: "5.1",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [{ id: "5.1.1", automated: true }],
  },
  {
    id: "5.2",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "manual",
    tests: [{ id: "5.2.1", automated: false }],
  },
  {
    id: "5.3",
    theme: 5,
    level: "A",
    wcag: ["1.3.1", "1.3.2"],
    automationLevel: "partial",
    tests: [{ id: "5.3.1", automated: false }],
  },
  {
    id: "5.4",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "full",
    tests: [{ id: "5.4.1", automated: true }],
  },
  {
    id: "5.5",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "manual",
    tests: [{ id: "5.5.1", automated: false }],
  },
  {
    id: "5.6",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "full",
    tests: [
      { id: "5.6.1", automated: true },
      { id: "5.6.2", automated: true },
    ],
  },
  {
    id: "5.7",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "full",
    tests: [
      { id: "5.7.1", automated: true },
      { id: "5.7.2", automated: true },
      { id: "5.7.3", automated: true },
    ],
  },
  {
    id: "5.8",
    theme: 5,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "full",
    tests: [{ id: "5.8.1", automated: true }],
  },
];

// ─── Theme 6 — Links ──────────────────────────────────────────────────────────
const theme6: CriterionDefinition[] = [
  {
    id: "6.1",
    theme: 6,
    level: "A",
    wcag: ["2.4.4", "2.4.9"],
    automationLevel: "partial",
    tests: [
      { id: "6.1.1", automated: true },
      { id: "6.1.2", automated: true },
      { id: "6.1.3", automated: true },
      { id: "6.1.4", automated: true },
      { id: "6.1.5", automated: false },
    ],
  },
  {
    id: "6.2",
    theme: 6,
    level: "A",
    wcag: ["4.1.2"],
    automationLevel: "full",
    tests: [{ id: "6.2.1", automated: true }],
  },
];

// ─── Theme 7 — Scripts ────────────────────────────────────────────────────────
const theme7: CriterionDefinition[] = [
  {
    id: "7.1",
    theme: 7,
    level: "A",
    wcag: ["4.1.2"],
    automationLevel: "partial",
    tests: [
      { id: "7.1.1", automated: false },
      { id: "7.1.2", automated: false },
      { id: "7.1.3", automated: false },
    ],
  },
  {
    id: "7.2",
    theme: 7,
    level: "A",
    wcag: ["4.1.2"],
    automationLevel: "manual",
    tests: [{ id: "7.2.1", automated: false }],
  },
  {
    id: "7.3",
    theme: 7,
    level: "A",
    wcag: ["2.1.1"],
    automationLevel: "partial",
    tests: [
      { id: "7.3.1", automated: false },
      { id: "7.3.2", automated: false },
    ],
  },
  {
    id: "7.4",
    theme: 7,
    level: "A",
    wcag: ["3.2.1", "3.2.2"],
    automationLevel: "manual",
    tests: [{ id: "7.4.1", automated: false }],
  },
  {
    id: "7.5",
    theme: 7,
    level: "AA",
    wcag: ["4.1.3"],
    automationLevel: "full",
    tests: [
      { id: "7.5.1", automated: true },
      { id: "7.5.2", automated: true },
      { id: "7.5.3", automated: true },
    ],
  },
];

// ─── Theme 8 — Mandatory Elements ─────────────────────────────────────────────
const theme8: CriterionDefinition[] = [
  {
    id: "8.1",
    theme: 8,
    level: "A",
    wcag: ["4.1.1"],
    automationLevel: "full",
    tests: [
      { id: "8.1.1", automated: true },
      { id: "8.1.2", automated: true },
      { id: "8.1.3", automated: true },
    ],
  },
  {
    id: "8.2",
    theme: 8,
    level: "A",
    wcag: ["4.1.1", "4.1.2"],
    automationLevel: "full",
    tests: [{ id: "8.2.1", automated: true }],
  },
  {
    id: "8.3",
    theme: 8,
    level: "A",
    wcag: ["3.1.1"],
    automationLevel: "full",
    tests: [{ id: "8.3.1", automated: true }],
  },
  {
    id: "8.4",
    theme: 8,
    level: "A",
    wcag: ["3.1.1"],
    automationLevel: "full",
    tests: [{ id: "8.4.1", automated: true }],
  },
  {
    id: "8.5",
    theme: 8,
    level: "A",
    wcag: ["2.4.2"],
    automationLevel: "full",
    tests: [{ id: "8.5.1", automated: true }],
  },
  {
    id: "8.6",
    theme: 8,
    level: "A",
    wcag: ["2.4.2"],
    automationLevel: "partial",
    tests: [{ id: "8.6.1", automated: true }],
  },
  {
    id: "8.7",
    theme: 8,
    level: "AA",
    wcag: ["3.1.2"],
    automationLevel: "partial",
    tests: [{ id: "8.7.1", automated: true }],
  },
  {
    id: "8.8",
    theme: 8,
    level: "AA",
    wcag: ["3.1.2"],
    automationLevel: "partial",
    tests: [{ id: "8.8.1", automated: true }],
  },
  {
    id: "8.9",
    theme: 8,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [{ id: "8.9.1", automated: true }],
  },
  {
    id: "8.10",
    theme: 8,
    level: "A",
    wcag: ["1.3.2"],
    automationLevel: "partial",
    tests: [{ id: "8.10.1", automated: true }],
  },
];

// ─── Theme 9 — Structure ──────────────────────────────────────────────────────
const theme9: CriterionDefinition[] = [
  {
    id: "9.1",
    theme: 9,
    level: "A",
    wcag: ["1.3.1", "2.4.6"],
    automationLevel: "full",
    tests: [
      { id: "9.1.1", automated: true },
      { id: "9.1.2", automated: true },
      { id: "9.1.3", automated: true },
    ],
  },
  {
    id: "9.2",
    theme: 9,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [
      { id: "9.2.1", automated: true },
      { id: "9.2.2", automated: true },
    ],
  },
  {
    id: "9.3",
    theme: 9,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "full",
    tests: [{ id: "9.3.1", automated: true }],
  },
  {
    id: "9.4",
    theme: 9,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [{ id: "9.4.1", automated: true }],
  },
];

// ─── Theme 10 — Presentation ──────────────────────────────────────────────────
const theme10: CriterionDefinition[] = [
  {
    id: "10.1",
    theme: 10,
    level: "A",
    wcag: ["1.3.3"],
    automationLevel: "partial",
    tests: [
      { id: "10.1.1", automated: false },
      { id: "10.1.2", automated: false },
      { id: "10.1.3", automated: false },
    ],
  },
  {
    id: "10.2",
    theme: 10,
    level: "A",
    wcag: ["1.3.3"],
    automationLevel: "manual",
    tests: [{ id: "10.2.1", automated: false }],
  },
  {
    id: "10.3",
    theme: 10,
    level: "A",
    wcag: ["1.3.2"],
    automationLevel: "manual",
    tests: [{ id: "10.3.1", automated: false }],
  },
  {
    id: "10.4",
    theme: 10,
    level: "AA",
    wcag: ["1.4.4"],
    automationLevel: "full",
    tests: [
      { id: "10.4.1", automated: true },
      { id: "10.4.2", automated: true },
      { id: "10.4.3", automated: true },
    ],
  },
  {
    id: "10.5",
    theme: 10,
    level: "A",
    wcag: ["1.4.8"],
    automationLevel: "partial",
    tests: [{ id: "10.5.1", automated: true }],
  },
  {
    id: "10.6",
    theme: 10,
    level: "A",
    wcag: ["1.4.1"],
    automationLevel: "partial",
    tests: [{ id: "10.6.1", automated: true }],
  },
  {
    id: "10.7",
    theme: 10,
    level: "AA",
    wcag: ["2.4.7"],
    automationLevel: "full",
    tests: [{ id: "10.7.1", automated: true }],
  },
  {
    id: "10.8",
    theme: 10,
    level: "A",
    wcag: ["1.3.2", "4.1.2"],
    automationLevel: "partial",
    tests: [
      { id: "10.8.1", automated: true },
      { id: "10.8.2", automated: true },
    ],
  },
  {
    id: "10.9",
    theme: 10,
    level: "A",
    wcag: ["1.3.3"],
    automationLevel: "manual",
    tests: [{ id: "10.9.1", automated: false }],
  },
  {
    id: "10.10",
    theme: 10,
    level: "A",
    wcag: ["1.3.3"],
    automationLevel: "manual",
    tests: [{ id: "10.10.1", automated: false }],
  },
  {
    id: "10.11",
    theme: 10,
    level: "AA",
    wcag: ["1.4.10"],
    automationLevel: "partial",
    tests: [
      { id: "10.11.1", automated: true },
      { id: "10.11.2", automated: true },
    ],
  },
  {
    id: "10.12",
    theme: 10,
    level: "AA",
    wcag: ["1.4.12"],
    automationLevel: "full",
    tests: [{ id: "10.12.1", automated: true }],
  },
  {
    id: "10.13",
    theme: 10,
    level: "AA",
    wcag: ["1.4.13"],
    automationLevel: "partial",
    tests: [
      { id: "10.13.1", automated: false },
      { id: "10.13.2", automated: false },
      { id: "10.13.3", automated: false },
    ],
  },
  {
    id: "10.14",
    theme: 10,
    level: "A",
    wcag: ["1.4.13"],
    automationLevel: "partial",
    tests: [
      { id: "10.14.1", automated: false },
      { id: "10.14.2", automated: false },
    ],
  },
];

// ─── Theme 11 — Forms ─────────────────────────────────────────────────────────
const theme11: CriterionDefinition[] = [
  {
    id: "11.1",
    theme: 11,
    level: "A",
    wcag: ["1.3.1", "3.3.2"],
    automationLevel: "full",
    tests: [
      { id: "11.1.1", automated: true },
      { id: "11.1.2", automated: true },
      { id: "11.1.3", automated: true },
    ],
  },
  {
    id: "11.2",
    theme: 11,
    level: "A",
    wcag: ["2.4.6", "3.3.2"],
    automationLevel: "manual",
    tests: [
      { id: "11.2.1", automated: false },
      { id: "11.2.2", automated: false },
      { id: "11.2.3", automated: false },
      { id: "11.2.4", automated: false },
      { id: "11.2.5", automated: false },
    ],
  },
  {
    id: "11.3",
    theme: 11,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [{ id: "11.3.1", automated: false }],
  },
  {
    id: "11.4",
    theme: 11,
    level: "A",
    wcag: ["1.3.1", "3.3.2"],
    automationLevel: "partial",
    tests: [
      { id: "11.4.1", automated: false },
      { id: "11.4.2", automated: false },
      { id: "11.4.3", automated: false },
    ],
  },
  {
    id: "11.5",
    theme: 11,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [{ id: "11.5.1", automated: true }],
  },
  {
    id: "11.6",
    theme: 11,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "full",
    tests: [
      { id: "11.6.1", automated: true },
      { id: "11.6.2", automated: true },
    ],
  },
  {
    id: "11.7",
    theme: 11,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "manual",
    tests: [{ id: "11.7.1", automated: false }],
  },
  {
    id: "11.8",
    theme: 11,
    level: "A",
    wcag: ["1.3.1"],
    automationLevel: "partial",
    tests: [
      { id: "11.8.1", automated: true },
      { id: "11.8.2", automated: true },
    ],
  },
  {
    id: "11.9",
    theme: 11,
    level: "A",
    wcag: ["1.3.1", "2.4.6"],
    automationLevel: "partial",
    tests: [
      { id: "11.9.1", automated: true },
      { id: "11.9.2", automated: true },
    ],
  },
  {
    id: "11.10",
    theme: 11,
    level: "A",
    wcag: ["3.3.1", "3.3.3"],
    automationLevel: "partial",
    tests: [
      { id: "11.10.1", automated: false },
      { id: "11.10.2", automated: false },
      { id: "11.10.3", automated: false },
      { id: "11.10.4", automated: false },
    ],
  },
  {
    id: "11.11",
    theme: 11,
    level: "A",
    wcag: ["3.3.3"],
    automationLevel: "partial",
    tests: [
      { id: "11.11.1", automated: false },
      { id: "11.11.2", automated: false },
    ],
  },
  {
    id: "11.12",
    theme: 11,
    level: "AA",
    wcag: ["3.3.4"],
    automationLevel: "manual",
    tests: [
      { id: "11.12.1", automated: false },
      { id: "11.12.2", automated: false },
    ],
  },
  {
    id: "11.13",
    theme: 11,
    level: "AA",
    wcag: ["1.3.5"],
    automationLevel: "full",
    tests: [{ id: "11.13.1", automated: true }],
  },
];

// ─── Theme 12 — Navigation ────────────────────────────────────────────────────
const theme12: CriterionDefinition[] = [
  {
    id: "12.1",
    theme: 12,
    level: "AA",
    wcag: ["2.4.5"],
    automationLevel: "partial",
    tests: [{ id: "12.1.1", automated: false }],
  },
  {
    id: "12.2",
    theme: 12,
    level: "AA",
    wcag: ["3.2.3"],
    automationLevel: "partial",
    tests: [
      { id: "12.2.1", automated: false },
      { id: "12.2.2", automated: false },
    ],
  },
  {
    id: "12.3",
    theme: 12,
    level: "AA",
    wcag: ["2.4.5"],
    automationLevel: "manual",
    tests: [{ id: "12.3.1", automated: false }],
  },
  {
    id: "12.4",
    theme: 12,
    level: "AA",
    wcag: ["2.4.5"],
    automationLevel: "partial",
    tests: [{ id: "12.4.1", automated: false }],
  },
  {
    id: "12.5",
    theme: 12,
    level: "AA",
    wcag: ["2.4.5"],
    automationLevel: "partial",
    tests: [{ id: "12.5.1", automated: false }],
  },
  {
    id: "12.6",
    theme: 12,
    level: "A",
    wcag: ["1.3.1", "2.4.1"],
    automationLevel: "full",
    tests: [
      { id: "12.6.1", automated: true },
      { id: "12.6.2", automated: true },
    ],
  },
  {
    id: "12.7",
    theme: 12,
    level: "A",
    wcag: ["2.4.1"],
    automationLevel: "full",
    tests: [{ id: "12.7.1", automated: true }],
  },
  {
    id: "12.8",
    theme: 12,
    level: "A",
    wcag: ["2.4.3"],
    automationLevel: "partial",
    tests: [{ id: "12.8.1", automated: true }],
  },
  {
    id: "12.9",
    theme: 12,
    level: "A",
    wcag: ["2.1.2"],
    automationLevel: "full",
    tests: [{ id: "12.9.1", automated: true }],
  },
  {
    id: "12.10",
    theme: 12,
    level: "A",
    wcag: ["2.1.4"],
    automationLevel: "manual",
    tests: [
      { id: "12.10.1", automated: false },
      { id: "12.10.2", automated: false },
      { id: "12.10.3", automated: false },
    ],
  },
  {
    id: "12.11",
    theme: 12,
    level: "AA",
    wcag: ["1.4.13"],
    automationLevel: "partial",
    tests: [
      { id: "12.11.1", automated: false },
      { id: "12.11.2", automated: false },
      { id: "12.11.3", automated: false },
    ],
  },
];

// ─── Theme 13 — Consultation ──────────────────────────────────────────────────
const theme13: CriterionDefinition[] = [
  {
    id: "13.1",
    theme: 13,
    level: "A",
    wcag: ["2.2.1"],
    automationLevel: "manual",
    tests: [
      { id: "13.1.1", automated: false },
      { id: "13.1.2", automated: false },
      { id: "13.1.3", automated: false },
      { id: "13.1.4", automated: false },
    ],
  },
  {
    id: "13.2",
    theme: 13,
    level: "A",
    wcag: ["3.2.2"],
    automationLevel: "partial",
    tests: [{ id: "13.2.1", automated: true }],
  },
  {
    id: "13.3",
    theme: 13,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "manual",
    tests: [{ id: "13.3.1", automated: false }],
  },
  {
    id: "13.4",
    theme: 13,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "partial",
    tests: [{ id: "13.4.1", automated: false }],
  },
  {
    id: "13.5",
    theme: 13,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "partial",
    tests: [{ id: "13.5.1", automated: true }],
  },
  {
    id: "13.6",
    theme: 13,
    level: "A",
    wcag: ["1.1.1"],
    automationLevel: "partial",
    tests: [{ id: "13.6.1", automated: false }],
  },
  {
    id: "13.7",
    theme: 13,
    level: "A",
    wcag: ["2.3.1"],
    automationLevel: "manual",
    tests: [{ id: "13.7.1", automated: false }],
  },
  {
    id: "13.8",
    theme: 13,
    level: "A",
    wcag: ["2.2.2"],
    automationLevel: "partial",
    tests: [
      { id: "13.8.1", automated: true },
      { id: "13.8.2", automated: true },
    ],
  },
  {
    id: "13.9",
    theme: 13,
    level: "AA",
    wcag: ["1.3.4"],
    automationLevel: "partial",
    tests: [{ id: "13.9.1", automated: true }],
  },
  {
    id: "13.10",
    theme: 13,
    level: "A",
    wcag: ["2.5.1"],
    automationLevel: "manual",
    tests: [
      { id: "13.10.1", automated: false },
      { id: "13.10.2", automated: false },
    ],
  },
  {
    id: "13.11",
    theme: 13,
    level: "A",
    wcag: ["2.5.2"],
    automationLevel: "partial",
    tests: [{ id: "13.11.1", automated: true }],
  },
  {
    id: "13.12",
    theme: 13,
    level: "A",
    wcag: ["2.5.4"],
    automationLevel: "manual",
    tests: [
      { id: "13.12.1", automated: false },
      { id: "13.12.2", automated: false },
      { id: "13.12.3", automated: false },
    ],
  },
];

// ─── Full catalog ─────────────────────────────────────────────────────────────

export const THEMES: ThemeDefinition[] = [
  { id: 1, criteria: theme1 },
  { id: 2, criteria: theme2 },
  { id: 3, criteria: theme3 },
  { id: 4, criteria: theme4 },
  { id: 5, criteria: theme5 },
  { id: 6, criteria: theme6 },
  { id: 7, criteria: theme7 },
  { id: 8, criteria: theme8 },
  { id: 9, criteria: theme9 },
  { id: 10, criteria: theme10 },
  { id: 11, criteria: theme11 },
  { id: 12, criteria: theme12 },
  { id: 13, criteria: theme13 },
];

export const ALL_CRITERIA: CriterionDefinition[] = THEMES.flatMap((t) => t.criteria);

export const CRITERIA_BY_ID: Readonly<Record<string, CriterionDefinition>> = Object.fromEntries(
  ALL_CRITERIA.map((c) => [c.id, c]),
);

export const TOTAL_CRITERIA = ALL_CRITERIA.length;
